OBJS=	BITMAP.OBJ CGA.OBJ COLOR.OBJ DETECT.OBJ DITHER.OBJ EGA.OBJ GLOBALS.OBJ MDA.OBJ SHOW.OBJ SYSTEM.OBJ VGA.OBJ
PRG=	show.exe
CFLAGS=	-c -ms -G -O -Z -f-

$(PRG): $(OBJS)
	tlink @tc.lnk
        
.C.OBJ:
	tcc $(CFLAGS) $<

clean:
	del *.exe
	del *.obj

