OBJS=	CGA.OBJ CPLUS.OBJ DETECT.OBJ DITHER.OBJ EGA.OBJ GLOBALS.OBJ MDA.OBJ PCX.OBJ SHOW.OBJ SYSTEM.OBJ TCCOMPAT.OBJ VGA.OBJ
PRG=	show.exe
CFLAGS=	-c -mt -G -O -Z -f- -k-

$(PRG): $(OBJS)
	tlink @tc.lnk
        
.C.OBJ:
	tcc $(CFLAGS) $<

clean:
	del *.exe
	del *.obj

